name: build
run-name: build game
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - run: mkdir build
      - run: cd build
      - run: cmake ../CMakeLists.txt
      - run: make snake
      - run: make test
      - run: ./test



