name: build
run-name: build game
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make snake
      - run: make tests
      - run: ./tests



