name: build
run-name: build game
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir build
      - name: "build"
        working-directory: build
        run: | 
          cmake ../CMakeLists.txt
          make snake
          make test
          ./test



